### ISSUE TITLE
Release v0.3.0 broke compatibility after update dependencies

### ISSUE THREAD

**Issue by mcaimes** [ggicci/owl#7]
![image](https://github.com/ggicci/owl/assets/3933330/42cece25-1d89-4bd0-bcb7-1ba5191b3db1)

Suggestion: revert release and release a major version.

**Comment by ggicci** [comment]
Hi @marciocaimes, I've made a new release (v0.14.1) of httpin to use ggicci:owl@v0.4.0.

https://github.com/ggicci/httpin/pull/76
